import { useMemo, useState } from "react";
import { Image, Pressable, ScrollView, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { EditorialCard, GoldButton, SerifTitle, SectionLabel, mirrorPalette } from "@/components/mirror-ui";
import type { Look, StylingSession } from "@/shared/types";

export default function LooksScreen() {
  const params = useLocalSearchParams<{ session?: string }>();
  const session = useMemo<StylingSession | null>(() => { try { return params.session ? JSON.parse(params.session) : null; } catch { return null; } }, [params.session]);
  const looks = session?.looks ?? [];
  const [activeMood, setActiveMood] = useState("For this moment");

  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 42 }}>
    <View className="flex-row items-center justify-between pt-3"><View><SectionLabel>YOUR EDIT</SectionLabel><SerifTitle style={{ marginTop: 7 }}>Three ways to wear it</SerifTitle></View><View className="h-11 w-11 items-center justify-center rounded-full bg-[#F2EFE8] border border-border"><IconSymbol name="sparkles" size={20} color={mirrorPalette.gold} /></View></View>
    <Text className="mt-3 text-base leading-6 text-muted">Built around your occasion, your budget, and the pieces you already own.</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingTop: 18 }}><Text className="mr-1 self-center text-xs font-bold tracking-[1.2px] text-muted">BROWSE</Text>{["For this moment", "Quiet luxury", "A little color"].map((mood) => <Pressable key={mood} onPress={() => setActiveMood(mood)} style={({ pressed }) => [{ borderRadius: 18, backgroundColor: activeMood === mood ? mirrorPalette.charcoal : mirrorPalette.ivoryDark, paddingHorizontal: 13, paddingVertical: 9 }, pressed && { opacity: 0.75 }]} accessibilityRole="button" accessibilityState={{ selected: activeMood === mood }}><Text className={activeMood === mood ? "text-xs font-semibold text-[#FAF8F4]" : "text-xs font-semibold text-foreground"}>{mood}</Text></Pressable>)}</ScrollView>
    <Pressable onPress={() => router.push("/stylist")} style={({ pressed }) => [{ alignSelf: "flex-end", paddingVertical: 8 }, pressed && { opacity: 0.7 }]} accessibilityRole="button" accessibilityLabel="Ask your stylist about these looks"><Text className="text-xs font-bold text-primary">Ask your stylist →</Text></Pressable>
    <View className="mt-2 rounded-2xl bg-[#E8EEE9] p-4"><Text className="text-[11px] font-bold tracking-[1.8px] text-[#617267]">AGENT STATUS</Text><Text className="mt-1 text-sm font-semibold text-[#3E5044]">Matched products · checked budget · ready to preview</Text><View className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/70"><View className="h-full w-[78%] rounded-full bg-[#7A9E87]" /></View></View>
    {looks.map((look: Look, index) => <EditorialCard key={look.id} style={{ marginTop: 18, padding: 0, overflow: "hidden" }}><View className="relative"><Image source={{ uri: look.items[0]?.imageUrl }} className="h-56 w-full" resizeMode="cover" /><View className="absolute left-4 top-4 rounded-full bg-[#1C1C1E]/80 px-3 py-1.5"><Text className="text-[10px] font-bold tracking-[1.5px] text-[#E8D49A]">LOOK 0{index + 1}</Text></View></View><View className="p-5"><View className="flex-row items-start justify-between"><View className="flex-1 pr-3"><Text className="text-2xl text-foreground" style={{ fontFamily: "Georgia" }}>{look.title}</Text><Text className="mt-1 text-sm text-muted">{look.subtitle}</Text></View><Text className="text-xl font-bold text-primary">${(look.totalCents / 100).toFixed(0)}</Text></View><Text className="mt-4 text-sm leading-5 text-muted">{look.rationale}</Text><View className="mt-4 flex-row flex-wrap gap-2">{look.items.map((item) => <View key={item.id} className="rounded-full bg-[#F2EFE8] px-3 py-2"><Text className="text-xs font-semibold text-[#5A554E]">{item.owned ? "Owned · " : ""}{item.category}</Text></View>)}</View><GoldButton onPress={() => router.push({ pathname: "/try-on", params: { session: JSON.stringify(session), lookId: look.id } })} style={{ marginTop: 18 }}><Text className="font-bold text-white">Preview on me</Text></GoldButton></View></EditorialCard>)}
    {looks.length === 0 && <View className="mt-10 items-center rounded-3xl border border-dashed border-border p-8"><IconSymbol name="sparkles" size={28} color={mirrorPalette.gold} /><Text className="mt-4 text-center text-base font-semibold text-foreground">Your edit will appear here</Text><Text className="mt-2 text-center text-sm leading-5 text-muted">Start from Home to build a grounded, budget-aware edit.</Text><Pressable onPress={() => router.push("/")} style={{ paddingVertical: 14 }}><Text className="font-bold text-primary">Build a look →</Text></Pressable></View>}
  </ScrollView></ScreenContainer>;
}
