import { Alert, FlatList, Image, Pressable, Text, View } from "react-native";
import { router } from "expo-router";
import { useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { EditorialCard, SerifTitle, SectionLabel, mirrorPalette } from "@/components/mirror-ui";
import { trpc } from "@/lib/trpc";
import type { StylingSession } from "@/shared/types";

function ProfileLink({ icon, title, subtitle, onPress }: { icon: "bookmark" | "checkroom" | "chat" | "notifications"; title: string; subtitle: string; onPress: () => void }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [{ flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: mirrorPalette.border, paddingHorizontal: 14, paddingVertical: 13 }, pressed && { opacity: 0.7 }]} accessibilityRole="button" accessibilityLabel={title}><View className="h-9 w-9 items-center justify-center rounded-full bg-[#F2EFE8]"><IconSymbol name={icon} size={18} color={mirrorPalette.gold} /></View><View className="ml-3 flex-1"><Text className="text-sm font-semibold text-foreground">{title}</Text><Text className="mt-1 text-xs text-muted">{subtitle}</Text></View><IconSymbol name="chevron.right" size={18} color={mirrorPalette.muted} /></Pressable>;
}

export default function ProfileScreen() {
  const recent = trpc.styling.recent.useQuery({ limit: 6 });
  const [lastArchived, setLastArchived] = useState<string>();
  const archive = trpc.styling.archive.useMutation({ onSuccess: (_, variables) => { setLastArchived(variables.sessionId); recent.refetch(); } });
  const unarchive = trpc.styling.unarchive.useMutation({ onSuccess: () => { setLastArchived(undefined); recent.refetch(); } });
  const sessions = recent.data ?? [];
  const confirmArchive = (sessionId: string) => Alert.alert("Archive this edit?", "It will leave Recent Edits but remain safely stored.", [{ text: "Keep it", style: "cancel" }, { text: "Archive", style: "destructive", onPress: () => archive.mutate({ sessionId }) }]);

  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><FlatList data={sessions} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 42 }} ListHeaderComponent={<>
    <View className="flex-row items-center justify-between pt-3"><View><SectionLabel>YOUR SPACE</SectionLabel><SerifTitle style={{ marginTop: 7 }}>Profile</SerifTitle></View><Pressable onPress={() => router.push("/settings")} accessibilityRole="button" accessibilityLabel="Open settings" style={({ pressed }) => [{ width: 42, height: 42, borderRadius: 21, backgroundColor: mirrorPalette.ivoryDark, alignItems: "center", justifyContent: "center" }, pressed && { opacity: 0.7 }]}><IconSymbol name="person" size={20} color={mirrorPalette.charcoal} /></Pressable></View>
    <Text className="mt-3 text-base leading-6 text-muted">Keep the pieces and preferences that make your edits feel like you.</Text>
    <View className="mt-7 rounded-3xl bg-[#1C1C1E] p-5"><View className="flex-row items-center gap-4"><View className="h-14 w-14 items-center justify-center rounded-full bg-[#2C2C2E]"><IconSymbol name="sparkles" size={25} color={mirrorPalette.goldLight} /></View><View className="flex-1"><Text className="text-xl text-[#FAF8F4]" style={{ fontFamily: "Georgia" }}>Your style profile</Text><Text className="mt-1 text-xs text-[#A8A8AD]">Personalized edits, kept in your control.</Text></View></View><View className="mt-5 flex-row items-center justify-between border-t border-white/10 pt-4"><Text className="text-xs font-bold tracking-[1.4px] text-[#C9A84C]">PREMIUM STYLIST</Text><Text className="text-xs text-[#A8A8AD]">Style profile active</Text></View></View>
    <View className="mt-7"><SectionLabel>PRIVACY</SectionLabel><EditorialCard style={{ marginTop: 10, padding: 16 }}><View className="flex-row items-start"><IconSymbol name="sparkles" size={20} color={mirrorPalette.sage} /><View className="ml-3 flex-1"><Text className="font-semibold text-foreground">Your photos stay yours</Text><Text className="mt-2 text-sm leading-5 text-muted">Photos are used only to create the preview you request. Provider credentials stay on the backend, and sizing decisions remain with you and the merchant.</Text></View></View></EditorialCard></View>
    <View className="mt-7"><SectionLabel>EXPLORE</SectionLabel><View className="mt-2 overflow-hidden rounded-2xl border border-border bg-surface"><ProfileLink icon="bookmark" title="Saved snapshots" subtitle="Revisit your favorite edits" onPress={() => router.push("/saved")} /><ProfileLink icon="bookmark" title="Archived edits" subtitle="Restore or remove past edits" onPress={() => router.push("/archived-edits")} /><ProfileLink icon="checkroom" title="My wardrobe" subtitle="Keep owned pieces in every edit" onPress={() => router.push("/wardrobe")} /><ProfileLink icon="chat" title="Ask your stylist" subtitle="Shape the next look conversationally" onPress={() => router.push("/stylist")} /><ProfileLink icon="notifications" title="Notifications" subtitle="Stylist notes and catalog updates" onPress={() => router.push("/notifications")} /></View></View>
    <View className="mt-7 flex-row items-center justify-between"><SectionLabel>RECENT EDITS</SectionLabel>{sessions.length > 0 && <Text className="text-xs font-semibold text-primary">{sessions.length} saved</Text>}</View>
    {lastArchived ? <View className="mt-3 flex-row items-center justify-between rounded-xl bg-[#E8EEE9] px-3 py-2"><Text className="flex-1 text-xs text-[#617267]">Edit archived safely.</Text><Pressable onPress={() => unarchive.mutate({ sessionId: lastArchived })} disabled={unarchive.isPending} accessibilityRole="button" accessibilityLabel="Undo archive"><Text className="text-xs font-bold text-primary">Undo</Text></Pressable></View> : null}
  </>} renderItem={({ item }: { item: StylingSession }) => <EditorialCard style={{ marginTop: 10, padding: 12 }}><Pressable onPress={() => router.push({ pathname: "/looks", params: { session: JSON.stringify(item) } })} style={({ pressed }) => [{ flexDirection: "row", alignItems: "center" }, pressed && { opacity: 0.7 }]} accessibilityRole="button" accessibilityLabel={`Resume ${item.intent.occasion || "styling session"}`}><View className="mr-3 h-16 w-16 overflow-hidden rounded-2xl bg-[#E8EEE9]"><Image source={{ uri: item.vtoPreviewUrl || item.looks[0]?.items[0]?.imageUrl }} className="h-full w-full" /></View><View className="flex-1"><Text className="font-semibold text-foreground">{item.intent.occasion || "Styling session"}</Text><Text className="mt-1 text-xs text-muted">{item.intent.aesthetic} · {item.looks.length} looks · {item.status}</Text></View><IconSymbol name="chevron.right" size={20} color={mirrorPalette.sage} /></Pressable><Pressable onPress={() => confirmArchive(item.id)} disabled={archive.isPending} style={{ alignSelf: "flex-end", paddingHorizontal: 8, paddingVertical: 5, opacity: archive.isPending ? 0.5 : 1 }} accessibilityRole="button" accessibilityLabel="Archive styling session"><Text className="text-xs font-semibold text-muted">Archive</Text></Pressable></EditorialCard>} ListEmptyComponent={<View className="mt-5 items-center rounded-3xl border border-dashed border-border p-8"><IconSymbol name="bookmark" size={26} color={mirrorPalette.gold} /><Text className="mt-3 text-center text-base font-semibold text-foreground">No saved edits yet</Text><Text className="mt-2 text-center text-sm leading-5 text-muted">Build your first edit from Home and it will appear here for easy recovery.</Text></View>} ListFooterComponent={<View className="mt-8"><SectionLabel>ABOUT MIRRORCART</SectionLabel><Text className="mt-3 text-sm leading-5 text-muted">An agentic stylist that searches, composes, visualizes, and prepares the look—without taking the final purchase decision away from you.</Text></View>} /></ScreenContainer>;
}
