import { FlatList, Image, Pressable, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { EditorialCard, SectionLabel, SerifTitle, mirrorPalette } from "@/components/mirror-ui";
import { trpc } from "@/lib/trpc";
import type { StylingSession } from "@/shared/types";

export default function SavedScreen() {
  const recent = trpc.styling.recent.useQuery({ limit: 8 });
  const sessions = recent.data ?? [];
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><FlatList data={sessions} keyExtractor={(item) => item.id} numColumns={2} columnWrapperStyle={{ gap: 12 }} showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 40 }} ListHeaderComponent={<View className="w-full pt-3"><Pressable onPress={() => router.back()} accessibilityRole="button" accessibilityLabel="Back" style={{ paddingVertical: 6 }}><IconSymbol name="chevron.left" size={24} color={mirrorPalette.charcoal} /></Pressable><SectionLabel>SAVED</SectionLabel><SerifTitle style={{ marginTop: 7 }}>Your snapshots</SerifTitle><Text className="mt-3 text-base leading-6 text-muted">Keep the looks that feel like you. Revisit an edit whenever the moment comes back around.</Text></View>} renderItem={({ item }: { item: StylingSession }) => { const look = item.looks[0]; const imageUrl = item.vtoPreviewUrl || look?.items[0]?.imageUrl; return <EditorialCard style={{ marginTop: 18, flex: 1, overflow: "hidden", padding: 0 }}><Pressable onPress={() => router.push({ pathname: "/looks", params: { session: JSON.stringify(item) } })} style={({ pressed }) => [pressed && { opacity: 0.75 }]} accessibilityRole="button" accessibilityLabel={`Open saved ${item.intent.occasion || "look"}`}><View className="h-48 bg-[#E8EEE9]">{imageUrl ? <Image source={{ uri: imageUrl }} className="h-full w-full" resizeMode="cover" /> : <View className="flex-1 items-center justify-center"><IconSymbol name="image" size={25} color={mirrorPalette.sage} /></View>}</View><View className="p-3"><Text className="text-sm font-semibold text-foreground" numberOfLines={1}>{look?.title || item.intent.occasion || "Saved edit"}</Text><Text className="mt-1 text-xs text-muted" numberOfLines={1}>{item.intent.aesthetic}</Text><Text className="mt-3 text-xs font-bold text-primary">Open edit →</Text></View></Pressable></EditorialCard>; }} ListEmptyComponent={<View className="mt-7 w-full items-center rounded-3xl border border-dashed border-border p-8"><View className="h-16 w-16 items-center justify-center rounded-full bg-[#F2EFE8]"><IconSymbol name="bookmark" size={28} color={mirrorPalette.gold} /></View><Text className="mt-4 text-center text-xl text-foreground" style={{ fontFamily: "Georgia" }}>No snapshots yet</Text><Text className="mt-2 text-center text-sm leading-5 text-muted">Create a preview from Try On and it will be ready to revisit here.</Text><Pressable onPress={() => router.push("/try-on")} style={({ pressed }) => [{ marginTop: 18, borderRadius: 15, backgroundColor: mirrorPalette.gold, paddingHorizontal: 22, paddingVertical: 13 }, pressed && { opacity: 0.8 }]}><Text className="font-bold text-white">Open Try On</Text></Pressable></View>} /></ScreenContainer>;
}
