import { useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { SectionLabel, SerifTitle, mirrorPalette } from "@/components/mirror-ui";

function PreferenceRow({ title, subtitle, icon, value, onChange }: { title: string; subtitle: string; icon: "sparkles" | "camera.fill" | "person"; value?: boolean; onChange?: (next: boolean) => void }) {
  return <View className="flex-row items-center border-b border-border px-4 py-4"><View className="h-9 w-9 items-center justify-center rounded-full bg-[#F2EFE8]"><IconSymbol name={icon} size={18} color={mirrorPalette.gold} /></View><View className="ml-3 flex-1"><Text className="text-sm font-semibold text-foreground">{title}</Text><Text className="mt-1 text-xs text-muted">{subtitle}</Text></View>{value !== undefined && onChange ? <Pressable onPress={() => onChange(!value)} accessibilityRole="switch" accessibilityState={{ checked: value }} style={{ width: 48, height: 28, borderRadius: 14, backgroundColor: value ? mirrorPalette.gold : "#EAE7DF", justifyContent: "center", paddingHorizontal: 3 }}><View style={{ width: 22, height: 22, borderRadius: 11, backgroundColor: "#FFFFFF", alignSelf: value ? "flex-end" : "flex-start", boxShadow: "0px 1px 3px rgba(28,28,30,0.15)" }} /></Pressable> : <IconSymbol name="chevron.right" size={19} color={mirrorPalette.muted} />}</View>;
}

export default function SettingsScreen() {
  const [notifications, setNotifications] = useState(true);
  const [arHints, setArHints] = useState(true);
  const [haptics, setHaptics] = useState(true);
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 42 }}><View className="flex-row items-center pt-3"><Pressable onPress={() => router.back()} accessibilityRole="button" accessibilityLabel="Back" style={{ paddingRight: 14, paddingVertical: 6 }}><IconSymbol name="chevron.left" size={24} color={mirrorPalette.charcoal} /></Pressable><View className="flex-1"><SectionLabel>YOUR SPACE</SectionLabel><SerifTitle style={{ marginTop: 5 }}>Settings</SerifTitle></View></View><View className="mt-7 rounded-3xl bg-[#1C1C1E] p-5"><View className="flex-row items-center"><View className="h-14 w-14 items-center justify-center rounded-full bg-[#2C2C2E]"><IconSymbol name="person" size={25} color={mirrorPalette.goldLight} /></View><View className="ml-4"><Text className="text-xl text-[#FAF8F4]" style={{ fontFamily: "Georgia" }}>Your profile</Text><Text className="mt-1 text-xs text-[#A8A8AD]">Personalize the MirrorCart experience</Text></View></View></View><View className="mt-7"><SectionLabel>ACCOUNT</SectionLabel><View className="mt-2 overflow-hidden rounded-2xl border border-border bg-surface"><PreferenceRow title="Body profile" subtitle="Sizing preferences stay in your control" icon="person" onChange={() => router.push("/profile")} /><PreferenceRow title="Privacy & data" subtitle="Review photo and provider handling" icon="sparkles" onChange={() => router.push("/profile")} /></View></View><View className="mt-7"><SectionLabel>PREFERENCES</SectionLabel><View className="mt-2 overflow-hidden rounded-2xl border border-border bg-surface"><PreferenceRow title="Notifications" subtitle="Price drops, tips, and order updates" icon="sparkles" value={notifications} onChange={setNotifications} /><PreferenceRow title="AR hints" subtitle="Pose and lighting guidance" icon="camera.fill" value={arHints} onChange={setArHints} /><PreferenceRow title="Haptic feedback" subtitle="Tactile response on primary actions" icon="sparkles" value={haptics} onChange={setHaptics} /></View></View><View className="mt-8 rounded-2xl bg-[#F2EFE8] p-4"><Text className="text-sm font-semibold text-foreground">Human approval stays on</Text><Text className="mt-1 text-sm leading-5 text-muted">MirrorCart never completes a purchase or sends a payment without your explicit approval.</Text></View><Text className="mt-8 text-center text-xs text-muted">MirrorCart · editorial styling for real life</Text></ScrollView></ScreenContainer>;
}
