import { FlatList, Pressable, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { EditorialCard, SectionLabel, SerifTitle, mirrorPalette } from "@/components/mirror-ui";
import { trpc } from "@/lib/trpc";

export default function WardrobeScreen() {
  const recent = trpc.styling.recent.useQuery({ limit: 8 });
  const owned = Array.from(new Set((recent.data ?? []).flatMap((session) => session.intent.ownedItems))).map((name, index) => ({ id: `${name}-${index}`, name }));
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><FlatList data={owned} keyExtractor={(item) => item.id} numColumns={2} columnWrapperStyle={{ gap: 12 }} showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 40 }} ListHeaderComponent={<View className="w-full pt-3"><Pressable onPress={() => router.back()} accessibilityRole="button" accessibilityLabel="Back" style={{ paddingVertical: 6 }}><IconSymbol name="chevron.left" size={24} color={mirrorPalette.charcoal} /></Pressable><SectionLabel>YOUR PIECES</SectionLabel><SerifTitle style={{ marginTop: 7 }}>My wardrobe</SerifTitle><Text className="mt-3 text-base leading-6 text-muted">Pieces you already own stay protected in every edit and never count toward the shopping total.</Text></View>} renderItem={({ item }) => <EditorialCard style={{ marginTop: 18, flex: 1, minHeight: 142, justifyContent: "space-between", padding: 16 }}><View className="h-10 w-10 items-center justify-center rounded-full bg-[#E8EEE9]"><IconSymbol name="checkroom" size={22} color={mirrorPalette.sage} /></View><Text className="mt-5 text-sm font-semibold leading-5 text-foreground">{item.name}</Text><Pressable onPress={() => router.push("/try-on")} accessibilityRole="button" accessibilityLabel={`Try ${item.name} on`} style={{ marginTop: 12 }}><Text className="text-xs font-bold text-primary">Try it on →</Text></Pressable></EditorialCard>} ListEmptyComponent={<View className="mt-7 w-full items-center rounded-3xl border border-dashed border-border p-8"><View className="h-16 w-16 items-center justify-center rounded-full bg-[#E8EEE9]"><IconSymbol name="checkroom" size={28} color={mirrorPalette.sage} /></View><Text className="mt-4 text-center text-xl text-foreground" style={{ fontFamily: "Georgia" }}>Start with what you own</Text><Text className="mt-2 text-center text-sm leading-5 text-muted">Tell MirrorCart about one of your pieces from Home, then we’ll keep it in every look.</Text><Pressable onPress={() => router.push("/")} style={({ pressed }) => [{ marginTop: 18, borderRadius: 15, backgroundColor: mirrorPalette.gold, paddingHorizontal: 22, paddingVertical: 13 }, pressed && { opacity: 0.8 }]}><Text className="font-bold text-white">Build a look</Text></Pressable></View>} /></ScreenContainer>;
}
